#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : dunst
Version  : 1.3.2
Release  : 2
URL      : https://github.com/dunst-project/dunst/archive/v1.3.2.tar.gz
Source0  : https://github.com/dunst-project/dunst/archive/v1.3.2.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause
Requires: dunst-data = %{version}-%{release}
Requires: dunst-license = %{version}-%{release}
BuildRequires : gdk-pixbuf-dev
BuildRequires : gtk+-dev
BuildRequires : pkgconfig(dbus-1)
BuildRequires : pkgconfig(libxdg-basedir)
BuildRequires : pkgconfig(xinerama)
BuildRequires : pkgconfig(xrandr)
BuildRequires : pkgconfig(xscrnsaver)

%description
[![Build Status](https://travis-ci.org/dunst-project/dunst.svg?branch=master)](https://travis-ci.org/dunst-project/dunst) [![Coverage Status](https://coveralls.io/repos/github/dunst-project/dunst/badge.svg?branch=coveralls)](https://coveralls.io/github/dunst-project/dunst?branch=master)

%package data
Summary: data components for the dunst package.
Group: Data

%description data
data components for the dunst package.


%package license
Summary: license components for the dunst package.
Group: Default

%description license
license components for the dunst package.


%prep
%setup -q -n dunst-1.3.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1541546617
make  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1541546617
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/dunst
cp LICENSE %{buildroot}/usr/share/package-licenses/dunst/LICENSE
%make_install

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/dbus-1/services/org.knopwob.dunst.service

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/dunst/LICENSE
